### ISSUE TITLE
Entity 클래스 오류

### ISSUE THREAD

**Issue by TreeJin99** [GDSC-PKNU-21-22/SogongSogong-back#12]
## Entity 패키지안에 있는 Entity 클래스들에 관한 문제이다.
- @Entity를 사용하면 오류 발생
- 하지만 실행이 불가능한 심각한 오류는 아니다.
- 웃긴건 다른 분 작업 환경에서는 오류가 발생하지 않고 오직 내 작업 환경에서만 오류가 발생한다.
- 결론. 무시해도 좋다.

**Comment by chodakk** [comment]
남우진만 오류 혼자 나서 어이없음

**Comment by chodakk** [comment]
해결 방법 : build.gradle 에 하단 내용을 추가한다.
`plugins{kotlin("plugin.jpa") version "1.6.10"}`
`noArg{annotation("javax.persistence.Entity"}`
