### ISSUE TITLE
Serialize에 대하여...

### ISSUE THREAD

**Issue by chodakk** [GDSC-PKNU-21-22/SogongSogong-back#25]
Serialize가 느리다는 이야기를 듣고.... Parcelable로 고치려함..^^

Kotlin은 kotlin-parcelize를 gradle에 포함시켜서 annotation으로 바로 사용 가능.
응 kotlin-parcelize  포함 불가능 선언.
더 구글링을 해보니 com.example.application...~~ 을 추가해서 사용하라함.
응 not found 에러.

포기하고 다른 방법을 찾았음.
kotlinx을 gradle에 넣으면 조금 더 효율적인 serialize가 가능하다!고 하였음.
serialize annotation 불러오기는 성공했는데, DTO에서 사용한 (java util) Date는 serialize할 수 없다고 오류가 뜸.
kotlinx의 DateTime이 따로 있다고 함.
하지만 쓰는 방법이 영......... 서버 시간을 그냥 그대로 적용하고 싶은데 그런게 안되나봄. (구글링해도 안나옴)

따라서 그냥 태초마을로 돌아갔다~

**Comment by Cha-Ji** [comment]
parcelable은 android 패키지 아닌가요?

date는 혹시 LocalDateTime은 어떠신지 모르겠네요

**Comment by chodakk** [comment]
parcelable android 패키지 맞아요.... 삽질하다 안드로이드인걸. .. 발견했습니다...

**Comment by chodakk** [comment]
헉 . . . . . . .LocalDateTime ....잘되네요....감사드립니다 .....
진작 여쭤볼걸..그랬네요
![image](https://user-images.githubusercontent.com/73934684/158064107-238224f7-82a6-4b4d-ab8a-4dc526e91548.png)
